### PR TITLE
changes for rails 6.1

### PR DESCRIPTION
**Pull request by jason-hobbs**

### CODE REVIEW

**Comment by ma3tk** [comment]
This pull-request seems to be nice. 

If contributors have time, could you please review this PR? :)
It looks okay to me.

**Comment by jason-hobbs** [comment]
I am currently getting undefined method `encode' for URI:Module when calling:
user.otp_provisioning_uri(label, issuer: issuer)

**Comment by yevhene** [comment]
@QuinnWilton or @bsedat Can you merge it and release a new version please?

**Comment by jason-hobbs** [comment]
[#185 ](https://github.com/tinfoil/devise-two-factor/pull/185) should be the one merged now.

**Pull request closed without merging**
