### PR TITLE
README improvements: Spelling, additional syntax highlighting/code blocks

### PR DESCRIPTION
**Pull request by connorshea**

### CODE REVIEW

**Comment by connorshea** [comment]
@bsedat @mattyb @ShaneWilton Don't mean to be rude, but in case you missed this last week.

See also #60

**Comment by bsedat** [comment]
Thank you for the contribution! The team is out of the office until after the new year, but we'll take a look as soon as we can. Sorry for the wait!

**Comment by bsedat** [comment]
Thanks for the contribution!

**Comment by bsedat** [comment]
(I'm slipping this in before @ShaneWilton realizes it removes his spelling of behaviour/behavior :stuck_out_tongue: )

**Pull request merged**
