### PR TITLE
Adds section about filtering sensitive parameters [ci-skip]

### PR DESCRIPTION
**Pull request by connorshea**

### CODE REVIEW

**Comment by connorshea** [comment]
Apologies for not properly skipping the CI check for my two PRs. Just README changes, so shouldn't be a problem to merge.

**Comment by bsedat** [comment]
I don't believe we need to recommend filtering out the iv, salt, and encrypted values. Those should never be set by a user.

It would be good practice to recommend filtering out the `otp_attempt` and `otp_secret` though. We should fix that in the example demo app as well.

**Comment by connorshea** [comment]
They're not set by the user, but they are a pretty big problem if your logs get leaked since your salt can be used to decrypt the encrypted values, no?

**Comment by bsedat** [comment]
Theoretically all 3 values could be leaked safely and useless without the associated decryption key.

Rails' parameter filtering I believe primarily affects incoming request logs, which shouldn't be containing the iv, salt, or encrypted value: http://api.rubyonrails.org/classes/ActionDispatch/Http/FilterParameters.html. The user will be submitting requests with `otp_attempt` during login though, and that should definitely be filtered out.

**Comment by ShaneWilton** [comment]
Both IVs and Salts are considered to be non-secret parameters. Feel free to filter them in your application if you want, but an attacker having knowledge of the IV (or salt) does nothing to allow that attacker to decrypt a ciphertext without the secret key.

Further, given that the IV and Salt are stored in the same location as the ciphertexts, it is difficult to imagine a scenario where the attacker has the secret and the ciphertext, but does not know the IV.

I do agree that `otp_attempt` and `otp_secret` should be filtered, however. We do this in our deployments of the gem, but forgot to include this in the readme. Nice catch!

**Comment by connorshea** [comment]
I've updated the PR to only include `otp_attempt` and `otp_secret`.

**Comment by bsedat** [comment]
I think we may want to just recommend filtering out `otp_attempt` only. `otp_secret`, `otp_backup_codes`, and `otp_backup_attempt` are implementation specific, so we probably shouldn't recommend people add them unless needed.

**Comment by connorshea** [comment]
Since the TwoFactorBackupable extension is used as an implementation example and included in the README, I'd argue that the note about filtering its relevant parameters is important to include.

**Comment by bsedat** [comment]
I believe Rails' parameter filtering only removes logging for matching named parameters from the access logs, so it requires clients to make requests containing those parameters. `otp_attempt` is the only one that this gem parses out and expects clients to be sending up.

Most clients probably would not submit `otp_secret` in a request; I was mistaken before when I thought it should be filtered. `otp_backup_codes` should not be user-settable either. I don't think `otp_backup_attempt` is parsed anywhere in this gem - TwoFactorBackupable checks the `otp_attempt` parameter as well.

**Comment by connorshea** [comment]
Is this acceptable now?

**Comment by bsedat** [comment]
Looks great to me! If you don't mind squashing those commits into one then I can merge. I appreciate you sticking it out with us.

**Comment by connorshea** [comment]
Squashed :)

**Comment by bsedat** [comment]
Thanks very much for the contribution!

**Pull request merged**
