### PR TITLE
Allow Rails 5.1

### PR DESCRIPTION
**Pull request by yskkin**
Since devise 4.3.0 also has the same restriction.

`bundle exec appraisal rails-5-1 rake test` passed locally

### CODE REVIEW

**Comment by bsedat** [comment]
Thanks so much! I'll try to get a release cut today or tomorrow.

**Comment by johnsudaar** [comment]
Any news on the release for rails 5.1? Thanks!

**Comment by bsedat** [comment]
Released v3.0.2 with the changes. Sorry it got lost for a little bit!

**Comment by johnsudaar** [comment]
Thanks a lot!

**Pull request merged**
