### PR TITLE
issue #115: bump the attr_encrypted version

### LINKED ISSUE #115: Rails 5 deprecation warning
```
DEPRECATION WARNING: otp_secret is not an attribute known to Active Record. This behavior is deprecated and will be removed in the next version of Rails. If you'd like otp_secret to be managed by Active Record, add `attribute :otp_secret to your class....
```

### PR DESCRIPTION
**Pull request by Mifrill**
closes #115

### CODE REVIEW

**Comment by mediafinger** [comment]
This PR can be closed, as the change is on master by now.

**Comment by Mifrill** [comment]
@mediafinger sorry, do I miss something? Issue #115 still opened and I didn't see those changes in master as well

**Comment by mediafinger** [comment]
Hey @Mifrill, sorry it is 18 months later and I don't have any memories of this and can't remember the context. Not sure if my comment was wrong back then or is now. However it may be, I don't have any merge rights, so I'm unable to help you out.

**Comment by Mifrill** [comment]
@mediafinger okay, thanks for the response!

**Comment by Mifrill** [comment]
Hello, @bsedat , can you take a look at this one? not sure why CI not triggered

**Comment by Mifrill** [comment]
Hey @tinfoil members, any chance to have it merged?

**Comment by Mifrill** [comment]
@tinfoil ping

**Comment by Mifrill** [comment]
Hi @tinfoil, any chance to have it merged?

**Comment by bsedat** [comment]
Thank you for the contribution, but this shouldn't be required any longer (see #115)

**Pull request closed without merging**
