### PR TITLE
Spec updates

### PR DESCRIPTION
**Pull request by mattyb**
Fixes tinfoil/devise-two-factor#49

### CODE REVIEW

**Comment by mattyb** [comment]
cc @f3ndot

**Comment by bsedat** [comment]
Thanks!

**Comment by mattyb** [comment]
Thanks for pulling! Will it take long to push the version?

**Comment by ShaneWilton** [comment]
I'll cut and deploy a release within the next hour and a half or so.

**Comment by mattyb** [comment]
Thanks!

**Comment by ShaneWilton** [comment]
Something came up, and I won't have a chance to do this tonight. I'll deploy it first thing in the morning though!

**Comment by ShaneWilton** [comment]
This has been pushed to Rubygems now. Sorry about the delay!

**Pull request merged**
