### PR TITLE
Devise 4

### LINKED ISSUE #83: Merge devise-4 branch into master and release v3.0.0
Devise 4.0 was released last week: https://rubygems.org/gems/devise/versions/4.0.0

Probably worth upgrading now.

### PR DESCRIPTION
**Pull request by connorshea**
Fixes #83 

I didn't actually know I could do this without either forking the project or having commit access, cool :D

### CODE REVIEW

**Comment by bsedat** [comment]
I plan to make a bugfix release for #79 early next week, and then we'll merge this in and increment to 3.0.0.

**Comment by connorshea** [comment]
Also make sure to change attr_encrypted 2.0 in the UPGRADING.md to 3.0 and warn against using 2.x due to the security vulnerability.

**Comment by bsedat** [comment]
@connorshea Do you need us to push the v3.0.0.pre1 version to Rubygems?

**Comment by connorshea** [comment]
Prerelease shouldn't be necessary since I already tested it by pointing the Gemfile to my fork, but if you want me to test again just in case I can.

**Comment by connorshea** [comment]
@bsedat upgrading to 3.0.0 was just merged into GitLab: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4216

:D Thanks for the help! Hopefully we won't have to report any bugs :)

**Pull request merged**
