### PR TITLE
Replace `attr_encrypted` with Rails 7 ActiveRecord::Encryption

### PR DESCRIPTION
**Pull request by andyjeffries**
In relation to my comment at https://github.com/tinfoil/devise-two-factor/pull/204#issuecomment-1104384113 this PR brings over Cybersecuricy's fix written by @dark-panda to the mainline branch. I didn't do any of the work other than copying a commit around and bringing in a Rails 7 fix (this may need to be done in a different way if it doesn't work on Rails 6 though)

Credit goes entirely to dark-panda from https://github.com/cybersecuricy/devise-two-factor/commit/87036f3b2e3cf60e8f84bb77c381d61bd9b76dbf

I'm just trying to get this working again for my own project...

### CODE REVIEW

**Comment by dark-panda** [comment]
@andyjeffries I've pushed up a new version of this branch to my personal fork at https://github.com/dark-panda/devise-two-factor/tree/fixes-rails-7 to modify the email address and I've rebased it off of the main branch. Perhaps this branch should be used instead? It isn't any different than the cybersecuricy branch, I've just switched it to my personal fork rather than my work's fork.

**Comment by andyjeffries** [comment]
I've got absolutely no objection to that. I just wanted it on the main repo, if you want it to be coming purely from you, absolutely no objection at all. Happy to close this PR if you've raised one?

**Comment by jgorniak** [comment]
Hey! Thanks Guys for your work 👍  Any news about this fix? It would be really nice to have it in official repo.

**Comment by dark-panda** [comment]
PR opened in #212.

**Pull request closed without merging**
